* Frameworks
  There is wide variety of options for machine learning frameworks in general and also for *CNN* specifically.
Namely there is a variety of tools that are centered around python. All of the frameworks bellow have at least some support for GPGPU computation.

** python
    Theano - Optimized and efficient open sourced python library that is widely used for computation with multi-dimensional arrays for thee needs of Machine learning.

    TensorFlow - Open source library developed by Google for numerical computations using data flow graphs.

    keras - High level Neural Network library that can run on top of either TensorFlow or Theano.
    
    scikit learn

** Lua
    Torch - Scientific computing framework with support of wide variety of machine learning algorithms.

** C++
    OpenCV - Library for computer vision and machine learning.

    Caffe - Deep learning framework. Also supports python API.

** Matlab
    MatConvNet - Matlab toolbox implementing CNNs for computer vision application.
    

In term of this Semestral project
For  the needs of this Semestral Project were selected two different frameworks to test capiabilities of Deep learnigng frameworks.

1. keras with support of Tensor Flow
2. torch (also possibly its python version pyTorch)


