* Image Processing
  Even thought that neural networks and machine learning exists as field of study since 1950 or sooner, there was no wider adoption of these techniques in image processing. Research in image processing was adopting predominately bottom up methodologies. Methods that were trying algorithmically describe image by detecting points of interest (e.g edges) in images. And then combine points to patches that were usually descibed by several paramters and these would be. In the first attempts to process image with use of machine learning were exactly these descriptors used as input. In other words complexity of image scenary was simplified to greatly reduce number of information supplied for any learning algorithm. Consequence of this approche is that this image preprocessing eables the deployment of often simple Machine learning algorithms for needs of pattern matching or image classification etc. As it might be obvious this favors simpler models.

As it was already expressed Machine learning techniques and models were
The advent of Machine

Fisrt attmpts to employ machine learning techniques in image processing ware dealing with the problem that input image cannot be used as input into any model directly. In other words image had to be processed and analized to determine higher order fetures in the image before they could be send into the model.
First problem with this  is that entire depoloyed stack is not wery modulable and to specialized too much (lacks generalization abilities). Second problem is often the fact that because image has to be preprocesd before it is feeded into machine learning model it demands extra time and resources. This can created problems in training face but also during operation after deployment. In practical terms this is often solved by very fast DSP.
This is problem less and less with techincal inovation but it still is not negligable (at least it has negative affect on the price of the solution).

This is exactly what makes deep learning models so usefull. For example in case of CNNs there is almost no need to process input image before it is used to train the model. Hiearchical extraction of image features that is automatically created by CNN is very advantages in this case.
