* Tasks:
** Research theory of NN and Convolution NN and send me a short research in order to set a common theme (draft of 2-5 pages)
*** convolution neural network
**** History
Evolution of Artificial Neural Network concept begun with Warren McCulloch and Walter Pitts in 1943, when they devised mathematical models inspired by the biology of Neuron cell. Another noteworthy step of the Neural Networks evolution was Perceptron created in 1958 by Frank Rosenblatt.
Perceptron sounded promising, but after several years of development it's promising potential wasn't fulfilled.

The last straw of the Perceptron model was criticism regarding its modeling capabilities. Which was mainly voiced by Marvin Minsky. The criticism was centered around the fact that there was no efficient way how to train it and also it's inability to solve XOR problem.
Even thought according to Minsky this criticism wasn't malicious, it stunned the interest in Neural networks for over a decade.
In the mid 80 Neural Network meet resurgence thanks to invention of Backpropagation.

even with all the advancement of Perceptron, which offered powerful computational model that enable to solve many technical problems, the promise of usage of potential that was promised by its biological counterpart was still sorely lacking.

[[explain what was possible and why it wasn't enogh]]


In hindsight there were two problems with this approach. Firstly there weren't enough data and secondly the technology (computational power as well as computational techniques) at that time weren't powerful enough to train sufficiently large and complex networks. Both of these were bridged by introduction of methods that fall under umbrella term Deep Learning (specifically Deep neural network). The word deep signifies that depth (number of hidden layers) of these networks is large. First problem was solved simply by availability of more data. These were obtained mainly thanks to effort of large companies (Google, Facebook, Youtube, etc.) but also with effort of large community of professionals and hobbyists of data science.
Both innovation in computational hardware and improvement of training methods were needed to solve the second problem. One of the technical breakthroughs was utilization of General-Purpose computing on Graphics Processing Units (GPGPU). Thanks to the fact that training process of Neural networks is basically large number of simple consequent computations there is a great potential for parallelization. Which is specifically true in case of Convolutional neural networks.

[[Convolution Neural networks are typically networks with many hidden layers that are using convolution of inputs as the means to propagate the signal through network.]]

*** Structure of CNN
    Structure of Convolutional networks is typically composed of three different types of layers. Stack of the layers can pretty much arbitrarily combine different types of layers with exception of Fully-Connected layers, which always come last.

**** Convolutional
     Each layer of this type is processing information from previous layer by convolution of input image with predefined filter. Each Convolutional layer is composed of outputs from applying of multiple different filters. Each of these filters is designed to underline different features of input image.

**** Max-Pooling
     This layer is used to down sample size of the input layer. Typically the input layer is divided into smaller equal rectangular matrices which are replaced by its largest element. This way is decreased the size of current layer and the information contained is compressed.

**** Fully-Connected
     Fully-Connected layer is typical layer from classical Neural Network and it is always located on the end of the layer stack. In other words it is never followed by another Convolutional layer.

** Attempt to find several basic articles (of type overview), which connects problematic CNN
** Potential Frameworks
   There is wide variety of options of frameworks for machine learning in general and also for CNN specifically.
Namely there is a variety of tools that are centered around python.

*** python
    Theano
    TensorFlow
    keras

*** Lua
    Torch

*** C++
    OpenCV
    Caffe

*** Matlab
    MatConvNet
